docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: env variables
        command: env
        service: cli
    - run:
        name: drush cim
        command: drush -y cim
        service: cli
    - run:
        name: drush cr
        command: drush -y cr
        service: cli



environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "1 * * * *" # this will run the cron daily
        command: drush cron
        service: cli
